//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightsContext : DbContext
    {
        public FlightsContext()
            : base("name=FlightsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FlightsDetail> FlightsDetails { get; set; }
        public virtual DbSet<FlyAdmin> FlyAdmins { get; set; }
        public virtual DbSet<FlyRegister> FlyRegisters { get; set; }
        public virtual DbSet<FlyReservation> FlyReservations { get; set; }
        public virtual DbSet<FlyUser> FlyUsers { get; set; }
    }
}
