//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyReservation
    {
        public int TicketNo { get; set; }
        public string FlightId { get; set; }
        public Nullable<System.DateTime> DateOfBooking { get; set; }
        public Nullable<System.DateTime> JourneyDate { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string PassengerName { get; set; }
        public Nullable<long> ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> NoOfTickets { get; set; }
        public Nullable<decimal> TotalFare { get; set; }
        public string Status { get; set; }
    
        public virtual FlightsDetail FlightsDetail { get; set; }
    }
}
